version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - server-data:/app/storage
      - server-db:/app/db
    networks:
      - securenet

  client:
    build: ./client
    stdin_open: true
    tty: true
    volumes:
      - client-keys:/app/keys
    networks:
      - securenet
    depends_on:
      - server

volumes:
  server-data:
  server-db:
  client-keys:

networks:
  securenet:
    driver: bridge