version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - server-data:/app/storage
      - server-db:/app/db
    networks:
      - securenet

volumes:
  server-data:
  server-db:

networks:
  securenet:
    driver: bridge